plugins {
    id "com.android.application"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream ->
        localProperties.load(stream)
    }
}

android {
    namespace "com.dayslite.countdown"
    compileSdk 35
    buildToolsVersion "35.0.1"

    defaultConfig {
        applicationId "com.dayslite.countdown"
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName "1.0.7"
    }

    signingConfigs {
        release {
            def releaseStoreFile = localProperties.getProperty("RELEASE_STORE_FILE")
            if (releaseStoreFile != null) {
                storeFile rootProject.file(releaseStoreFile)
            }
            storePassword localProperties.getProperty("RELEASE_STORE_PASSWORD")
            keyAlias localProperties.getProperty("RELEASE_KEY_ALIAS")
            keyPassword localProperties.getProperty("RELEASE_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.json:json:20231013"
}
