plugins {
    id "com.android.application"
}

android {
    namespace "com.dayslite.countdown"
    compileSdk 35
    buildToolsVersion "35.0.1"

    defaultConfig {
        applicationId "com.dayslite.countdown"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}
